# Keywords to search for in the generated keys.
#
# The search is case-insensitive. You can list one or more keywords.
# If multiple keywords are given, the matching behavior is controlled
# by the `search.matching` section.
#
# Must contain at least one keyword.
keywords:
  - example
  - meow

search:
  # The fields to search within each generated key.
  #
  # Possible fields:
  # - public-key
  # - private-key
  # - sha1-fingerprint
  # - sha256-fingerprint
  # - sha384-fingerprint
  # - sha512-fingerprint
  #
  # Default:
  # - public-key
  # - sha256-fingerprint
  fields:
    - public-key
    - sha256-fingerprint

  # Matching rules when multiple keywords and/or fields are specified.
  #
  # For example:
  # - If both `all-keywords` and `all-fields` are true:
  #   - Every keyword must appear in every field to count as a match.
  # - If both are false:
  #   - At least one keyword must appear in at least one field to
  #     count as a match.
  # - If `all-keywords` is true and `all-fields` is false:
  #   - Every keyword must appear in at least one field to count as a match.
  # - If `all-keywords` is false and `all-fields` is true:
  #   - At least one keyword must appear in every field to count as a match.
  matching:
    # If set to true, all keywords must appear to count as a match.
    # If set to false, a match occurs if any keyword appears.
    #
    # This option works together with `all-fields`.
    #
    # Default: false
    all-keywords: false

    # If true, every specified field must contain matching keywords.
    # If false, at least one field needs to contain matching keywords.
    #
    # This option works together with `all-keywords`.
    #
    # Default: true
    all-fields: true

runtime:
  # Number of threads to use for key generation.
  #
  # Default: number of CPU cores.
  threads: 16

  # Prevent the system from sleeping while running.
  #
  # Default: true
  keep-awake: true

  # Pin key generation threads to specific CPU cores.
  # Can improve performance on some systems.
  #
  # Default: true
  pin-threads: true

  # TODO: Add `use-physical-cores` option to use only physical cores.

output:
  # Directory to save found keys.
  #
  # Default: found-keys
  save-to: found-keys
