[package]
name = "keep-awake"
version = "0.0.0"
edition = "2024"

[target.'cfg(target_os = "windows")'.dependencies]
windows = { version = "0.62.0", features = [
  "Win32_System_Power",
  "Win32_System_SystemServices",
  "Win32_System_Threading",
] }
